import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/auth-context";
import { FavoritesProvider } from "@/contexts/optimized-favorites-context";
import { CartProvider } from "@/contexts/cart-context";
import { ServerStatusProvider } from "@/contexts/server-status-context";
import { AppContentWrapper } from "@/components/app-content-wrapper";
import { FavoritesAuthSync } from "@/components/favorites-auth-sync";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ServerStatusProvider>
          <AppContentWrapper>
            <AuthProvider>
              <FavoritesProvider>
                <CartProvider>
                  <FavoritesAuthSync />
                  {children}
                  <Toaster expand position="bottom-right"/>
                </CartProvider>
              </FavoritesProvider>
            </AuthProvider>
          </AppContentWrapper>
        </ServerStatusProvider>
      </body>
    </html>
  );
}
