extends:
  - recommended

apis:
  main:
    root: docs/openapi.yaml

rules:
  no-unused-components: warn
  operation-description: warn
  operation-summary: warn
  tag-description: warn

theme:
  openapi:
    disableSearch: false
    showExtensions: true
    hideSingleRequestSampleTab: false
    expandSingleSchemaField: true
    schemaExpansionLevel: 2
    hideDownloadButton: false
    hideRequestPayloadSample: false
    hideSecuritySection: false
    hideHostname: false
    hideLoading: false
    nativeScrollbars: false
    pathInMiddlePanel: false
    expandResponses: ''
    showConsole: true
